<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Sinatra errors</title>
<link rel="stylesheet" type="text/css" href="../assets/css/styles.css">
</head>
<body>
<div class="container">
<a href="../index.html" class="back-link">&laquo; Back to Index</a>
<h1 id="sinatra-errors">Sinatra errors</h1>

<p><a href="https://gist.github.com/Integralist/45732badab5a807e1d133dc9ceed315b" target="_blank">View original Gist on GitHub</a></p>

<h2 id="sinatra-errors-rb">sinatra errors.rb</h2>

<pre><code class="language-ruby">require &quot;sinatra/base&quot;

class Foo &lt; Sinatra::Base
  def initialize
    configure
    super()
  end

  get &quot;/&quot; do
    &quot;hello&quot;
  end

  get &quot;/err&quot; do
    404 # shows no content (but go to /foo and you'll see Sinatra 404)
  end

  get &quot;/fail&quot; do
    fail &quot;wat?&quot; # this is rescued by main sinatra error method
  end

  error do
    # method typically used to show some kind of response to user
    # but not in our example here... instead we see what happens if this error method itself fails
    call_method_that_fails # depending on configure method being run: it should either show a safe Internal Server Error or revealing stack trace
  end

  private

  def configure
    self.class.tap do |s|
      s.configure { s.disable :show_exceptions, :raise_errors }
    end
  end

  def call_method_that_fails
    fail &quot;wat!?&quot; # shows different error page but still has backtrace?
  end
end
</code></pre>

</div>
</body>
</html>